// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngucdfeisojezussmagz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ndWNkZmVpc29qZXp1c3NtYWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTIxNDIsImV4cCI6MjA3NDEyODE0Mn0.6bDQsZ0-FlPM4bZB5hnk2P59D-Zns-AXsF-RNCNO0U4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});